[package]
name = "tract-rs"
version = "0.20.7-pre"
license = "MIT OR Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/sonos/tract"
keywords = [ "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2021"
rust-version = "1.65"
include = [ "Cargo.toml", "src/**/*.rs", "LICENSE*", "tests" ]

[dependencies]
anyhow.workspace = true
boow.workspace = true
flate2.workspace = true
half.workspace = true
ndarray.workspace = true
tract-api = { path = ".." }
tract-nnef = { path = "../../nnef/" }
tract-onnx-opl = { path = "../../onnx-opl/" }
tract-onnx = { path = "../../onnx/" }
tract-pulse = { path = "../../pulse/" }
tract-libcli = { path = "../../libcli" }
serde_json.workspace = true

[dev-dependencies]
reqwest.workspace = true
tempfile = "*"
serde_json = "*"

# [features]
# default = [ "dylib" ]
# dylib = []
# staticlib = []
